name: Python tests

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

jobs:
  python:
    # -- Python tests --
    #
    # This job tests the basic functionality
    # of htgettoken.
    #

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
          - Windows
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        # this is needed for conda environments to activate automatically
        shell: bash -el {0}

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          miniforge-variant: Mambaforge
          python-version: ${{ matrix.python-version }}
          use-mamba: true

      # install krb5 for gssapi
      - name: Install krb5
        run: mamba install krb5

      - name: Install htgettoken
        run: python -m pip install .

      - name: Package list
        run: python -m pip list installed

      - name: Show htgettoken info
        run: python -m pip show htgettoken

      - name: Test htgettoken
        run: htgettoken --help
