name: Python tests

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

jobs:
  python:
    # -- Python tests --
    #
    # This job tests the basic functionality
    # of htgettoken.
    #

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
          - Windows
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install krb5-config for gssapi
      # (this is needed because gssapi isn't installed from a wheel,
      #  but from the tarball, boo)
      - name: Install krb5-config for Linux
        if: matrix.os == 'Ubuntu'
        run: sudo apt-get -yqq update && sudo apt-get install -yqq libkrb5-dev

      - name: Install htgettoken
        run: python -m pip install .

      - name: Package list
        run: python -m pip list installed

      - name: Show htgettoken info
        run: python -m pip show htgettoken

      - name: Test htgettoken
        run: htgettoken --help
